name: example

on:
  push:

env:
   S3_ARN: ""
jobs:
  SsmParameter:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: 'ap-northeast-1' # リージョンを指定
          role-to-assume: 'arn:aws:iam::654654329506:role/GitHubActionAssumeRoleWithAction' # 作成した IAM ロールの ARN

      # プライベートな S3 バケットを読み取ってみる
      - run: |
          S3_ARN=aws ssm get-parameter --query "Parameter.Value" --output text --name "/TestS3/Arn"
          echo "S3のARN：$S3_ARN"
