name: example

on:
  push:

jobs:
  SsmParameter1:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: 'ap-northeast-1' # リージョンを指定
          role-to-assume: 'arn:aws:iam::654654329506:role/GitHubActionAssumeRoleWithAction' # 作成した IAM ロールの ARN

      - run: |
          # CDKでS3 バケット作成後にパラメータストアに登録したARNを取得
          bucketArn=$(aws ssm get-parameter --query "Parameter.Value" --output text --name "/TestS3/Arn")
          echo "S3のARN：$bucketArn"
          # S3 バケットにタグを設定する
          aws resourcegroupstaggingapi tag-resources --resource-arn-list $bucketArn --tags test=GithubActions
